heat_template_version: 2013-05-23

description: >
  Hello world HOT template that just defines a single server.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server

  flavor:
    type: string
    description: Flavor for the server to be created
    constraints:
      - allowed_values: [m1.large , m1.tiny]

  image:
    type: string
    description: Image ID or image name to use for the server


  network:
    type: string
    description: Network which attached to the server


resources:
  DB:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: [{network: { get_param: network }}]

  server2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: [{network: { get_param: network }}]

outputs:
  server_networks:
    description: server IP
    value: { get_attr: [DB, networks] }
  server2_networks:
    description: server IP
    value: { get_attr: [server2, networks] }