heat_template_version: 2014-10-16  
description: A simple auto scaling group.  Tony Cheng 2015/8/14 v1
resources:  
  group:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 3
      max_size: 5
      min_size: 1
      resource:
        type: OS::Nova::Server::Cirros
